spring.application.name=SmileCare

spring.datasource.url=jdbc:mysql://localhost:3306/session06_th?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.profiles.active=cloud
